name: Build dll

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --release --package arcdps_wvw

      - shell: bash
        run: |
          sha256sum target/release/arcdps_wvw.dll

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: dll
          path: target/release/arcdps_wvw.dll

